"""foregin key update

Revision ID: 35aa5c326029
Revises: 29005d530c8d
Create Date: 2025-04-16 01:10:31.594575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35aa5c326029'
down_revision: Union[str, None] = '29005d530c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'connectors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connectors', type_='foreignkey')
    # ### end Alembic commands ###
