"""update Connector table structure

Revision ID: 5b286feb734a
Revises: 35aa5c326029
Create Date: 2025-04-17 05:46:17.840813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b286feb734a'
down_revision: Union[str, None] = '35aa5c326029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connectors', sa.Column('connector_type', sa.String(), nullable=False))
    op.add_column('connectors', sa.Column('connection_details', sa.JSON(), nullable=True))
    op.drop_column('connectors', 'connection_uri')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connectors', sa.Column('connection_uri', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('connectors', 'connection_details')
    op.drop_column('connectors', 'connector_type')
    # ### end Alembic commands ###
